<?xml version="1.0"?>
<package format="3">
  <name>pib_description_v4</name>
  <version>0.1.0</version>
  <description>pib Roboter URDF (v4-Hand) mit ros2_control Hardware-Interface</description>
  <maintainer email="leonkrampf206@gmail.com">Leon</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>urdf</exec_depend>
  <exec_depend>xacro</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
